stages:         
# Set up two testing paths
  - setup
  - test
  - deploy
  - release

.setup_matlab_windows: &setup_matlab_windows
  - $env:MLM_LICENSE_TOKEN="$LICENSEOWNER|$LICENSELABEL|$LICENSETOKEN" # Set the batch token license
  - Set-Alias -Name matlab -Value "D:\MATLAB\$VERSION\bin\matlab-batch"

setup-job:
  tags:
    - training
    - windows
  stage: setup
  script:
    - cd ..
    - if (test-path utilities) { rm -r -force utilities }
    - git clone https://insidelabs-git.mathworks.com/modular-curriculum-content/utilities.git
    - cd $CI_PROJECT_NAME 
  allow_failure: false

smoke-test:
  parallel:
    matrix:
      - VERSION: [R2024b,R2025a,R2025b]
  tags:
    - training
    - windows
  stage: test
  script: 
    - *setup_matlab_windows
    - matlab "openProject(pwd);RunAllTests"
  when: always
  allow_failure: true
  artifacts:
    name: "$VERSION"
    paths:
      - public/*
    when:  always

pages:
  variables:
    VERSION: "R2025a"
  tags:
    - training
    - windows
  stage: deploy
  script:
    - *setup_matlab_windows
    - matlab "openProject(pwd);PostSmokeTest;"
  artifacts:
    paths:
      - public
        
file-test:   
  variables:
    VERSION: "R2025a"
  tags:
    - training
    - windows
  stage: release
  script: 
    - *setup_matlab_windows
    - matlab "proj = openProject(pwd); 
      addpath(proj.RootFolder+'/InternalFiles/Tests/CI');
      results = runtests('OpenCloseFileTest.m');
      disp(table(results)); assertSuccess(results);"
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH
      when: always
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != $CI_DEFAULT_BRANCH
      when: manual
  allow_failure: true

release-testing:
  variables:
    VERSION: "R2025a"
  tags:
    - training
    - windows
  stage: release
  script: 
    - matlab "proj = openProject(pwd); 
      cd ..;
      addpath(genpath(fullfile('utilities','TestingResources')));
      addpath(genpath(fullfile('utilities','Tools')));
      runCMTests"
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH
      when: always
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != $CI_DEFAULT_BRANCH
      when: manual
  allow_failure: true
